branches:
  only:
  - main

dist: trusty
sudo: true

language: node_js
node_js:
  - '14.0'

services:
  - docker

addons:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - cd covid-modelizer-app/src

install:
  - npm install

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose build
  - docker push $IMAGE_NAME:latest